contact_links:
  - name: Join nf-core
    url: https://nf-co.re/join
    about: Please join the nf-core community here
  - name: "Slack #wgcnamodules channel"
    url: https://nfcore.slack.com/channels/wgcnamodules
    about: Discussion about the nf-core/wgcnamodules pipeline
